### ISSUE TITLE
Low quality website

### ISSUE THREAD

**Issue by Quantum64** [silverex/silverex.github.io#1]
Consider improving website quality. Thanks.

**Comment by silverex** [comment]
I'll consider it if you add a remindme command to your skype bot.

**Comment by Quantum64** [comment]
Excuse me, this issue was not fully resolved.

**Comment by silverex** [comment]
I think it was.

**Comment by Quantum64** [comment]
Did you make that CSS?

**Comment by silverex** [comment]
Nope, it's a framework.
